import SwiftUI
import UIKit

/// Renders a printable one-page PDF of the current session.
enum HealthReport {
    @MainActor
    static func makePDF(store: VitalsStore, device: EVKManager) -> URL? {
        let view = ReportPage(store: store, device: device)
        let renderer = ImageRenderer(content: view)
        renderer.proposedSize = ProposedViewSize(width: 595, height: 842) // A4 @ 72 dpi
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("Health Report.pdf")
        var box = CGRect(x: 0, y: 0, width: 595, height: 842)
        guard let consumer = CGDataConsumer(url: url as CFURL),
              let ctx = CGContext(consumer: consumer, mediaBox: &box, nil) else { return nil }
        renderer.render { _, draw in
            ctx.beginPDFPage(nil)
            draw(ctx)
            ctx.endPDFPage()
        }
        ctx.closePDF()
        return url
    }
}

private struct ReportPage: View {
    let store: VitalsStore
    let device: EVKManager

    private var dateText: String {
        let f = DateFormatter()
        f.dateStyle = .long
        f.timeStyle = .short
        return f.string(from: Date())
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            Text("HEALTH REPORT")
                .font(.system(size: 22, weight: .heavy))
                .tracking(3)
            Text(dateText).font(.system(size: 12)).foregroundStyle(.secondary)
            Divider()
            metric("Heart rate", store.heartRate.map { "\($0) bpm" } ?? "--", store.heartRateSource == .waveform ? "from PPG waveform (sensor algorithm reported \(store.sensorHeartRate ?? 0))" : "confidence \(store.heartRateConfidence)/100 · zone \(store.zone)")
            metric("Blood oxygen (SpO₂)", store.spo2.map { "\($0) %" } ?? "--", store.spo2RValue.map { String(format: "R %.3f · level %d", $0, store.spo2Level) } ?? "")
            metric("Respiratory rate", store.respiratoryRate.map { String(format: "%.1f rpm", $0) } ?? "--", "estimated from PPG baseline")
            metric("Resting heart rate", store.restingHeartRate.map { "\($0) bpm" } ?? "--", "lowest 60-second average this session")
            metric("HRV (RMSSD)", store.hrv.map { String(format: "%.0f ms", $0) } ?? "--", "from sensor RR intervals")
            metric("Skin temperature", store.skinTempDelta.map { String(format: "%+.1f °C", $0) } ?? "n/a", "no temperature sensor on this module")
            metric("Wear", store.wear.label, "")
            Divider()
            Text("Sensor: Goodix GH3x2x EVK · \(device.firmwareVersion) · driver \(device.driverVersion)")
                .font(.system(size: 10)).foregroundStyle(.secondary)
            Text("Session: \(Int(store.sessionDuration / 60)) min · \(store.frames) frames · \(store.droppedFrames) dropped")
                .font(.system(size: 10)).foregroundStyle(.secondary)
            Text("Generated by GH Monitor. Not a medical device; for informational purposes only.")
                .font(.system(size: 9)).foregroundStyle(.secondary)
            Spacer()
        }
        .padding(48)
        .frame(width: 595, height: 842, alignment: .topLeading)
        .background(Color.white)
        .foregroundStyle(Color.black)
    }

    private func metric(_ title: String, _ value: String, _ note: String) -> some View {
        HStack(alignment: .firstTextBaseline) {
            VStack(alignment: .leading, spacing: 2) {
                Text(title.uppercased()).font(.system(size: 11, weight: .bold)).tracking(1.5).foregroundStyle(.secondary)
                if !note.isEmpty { Text(note).font(.system(size: 10)).foregroundStyle(.secondary) }
            }
            Spacer()
            Text(value).font(.system(size: 22, weight: .heavy))
        }
    }
}
